// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvgrorjrozwgobpxjreu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2Z3Jvcmpyb3p3Z29icHhqcmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDI5OTIsImV4cCI6MjA3MjUxODk5Mn0.2kRs9UNSnH9LynA6ItHaM1TprpKxaj8wVbT8W0yPYXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});